import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Header } from "@/components/layout/Header";
import { BottomNav } from "@/components/layout/BottomNav";
import { Button } from "@/components/ui/button";
import { Link, useNavigate } from "react-router-dom";
import { MetaHead } from "@/components/common/MetaHead";
import { ArrowLeft, Home } from "lucide-react";
const ScopeReductionGraphic = () => (_jsx("div", { className: "w-full max-w-[320px] aspect-[4/3] mx-auto relative mb-8", children: _jsxs("svg", { viewBox: "0 0 400 300", className: "w-full h-full text-text-primary", style: { overflow: 'visible' }, children: [_jsx("defs", { children: _jsx("pattern", { id: "grid", width: "20", height: "20", patternUnits: "userSpaceOnUse", children: _jsx("path", { d: "M 20 0 L 0 0 0 20", fill: "none", stroke: "currentColor", strokeWidth: "0.5", opacity: "0.1" }) }) }), _jsx("rect", { width: "100%", height: "100%", fill: "url(#grid)" }), _jsxs("g", { stroke: "currentColor", strokeWidth: "3", fill: "none", className: "text-text-primary", children: [_jsx("rect", { x: "50", y: "50", width: "300", height: "200" }), _jsx("line", { x1: "150", y1: "50", x2: "150", y2: "250" }), _jsx("line", { x1: "250", y1: "50", x2: "250", y2: "250" }), _jsx("line", { x1: "50", y1: "150", x2: "150", y2: "150" }), _jsx("line", { x1: "250", y1: "150", x2: "350", y2: "150" })] }), _jsxs("g", { stroke: "currentColor", strokeWidth: "1", fill: "none", opacity: "0.5", children: [_jsx("rect", { x: "60", y: "60", width: "40", height: "20" }), _jsx("circle", { cx: "80", cy: "90", r: "8" }), _jsx("rect", { x: "60", y: "160", width: "40", height: "60" }), _jsx("circle", { cx: "300", cy: "100", r: "20" }), _jsx("rect", { x: "270", y: "170", width: "60", height: "20" })] }), _jsx("path", { d: "M 160,110\n           q 10,-10 20,0 q 10,-10 20,0 q 10,-10 20,0 q 10,-10 20,0\n           q 10,10 0,20 q 10,10 0,20 q 10,10 0,20 q 10,10 0,20\n           q -10,10 -20,0 q -10,10 -20,0 q -10,10 -20,0 q -10,10 -20,0\n           q -10,-10 0,-20 q -10,-10 0,-20 q -10,-10 0,-20 q -10,-10 0,-20\n           z", fill: "none", stroke: "#ef4444", strokeWidth: "2" }), _jsxs("g", { className: "text-red-500", children: [_jsx("text", { x: "200", y: "145", fill: "#ef4444", textAnchor: "middle", className: "text-[10px] font-mono font-bold tracking-tighter", children: "ITEM DELETED" }), _jsx("text", { x: "200", y: "160", fill: "#ef4444", textAnchor: "middle", className: "text-[10px] font-mono font-bold tracking-tighter", children: "VALUE ENGINEERING" })] })] }) }));
const NotFound = () => {
    const navigate = useNavigate();
    return (_jsxs("div", { className: "min-h-screen bg-surface-default flex flex-col", children: [_jsx(MetaHead, { title: "404: Scope Reduction" }), _jsx("div", { className: "md:hidden", children: _jsx(Header, { showLogo: true }) }), _jsxs("main", { className: "flex-1 flex flex-col items-center justify-center py-16 px-8 text-center w-full", children: [_jsx(ScopeReductionGraphic, {}), _jsxs("div", { className: "space-y-6 max-w-2xl mx-auto", children: [_jsx("h1", { className: "text-4xl font-bold tracking-tight text-text-primary", children: "404: Scope Reduction" }), _jsx("div", { className: "bg-surface-muted/30 p-6 border border-border-default/50 rounded-sm", children: _jsx("p", { className: "text-sm md:text-base font-mono text-text-secondary leading-relaxed", children: "\"We regret to inform you that this page was removed from the project scope during the latest budget review. The client decided a white void was more cost-effective.\"" }) }), _jsxs("div", { className: "flex flex-col sm:flex-row items-center justify-center gap-4 pt-4", children: [_jsx(Button, { asChild: true, size: "lg", className: "min-w-[200px] border-2", variant: "default", children: _jsxs(Link, { to: "/", className: "flex items-center gap-2", children: [_jsx(Home, { className: "w-4 h-4" }), "Return to Approved Scope"] }) }), _jsx(Button, { onClick: () => navigate(-1), size: "lg", variant: "outline", className: "min-w-[200px] border-2", children: _jsxs("span", { className: "flex items-center gap-2", children: [_jsx(ArrowLeft, { className: "w-4 h-4" }), "View Change Order"] }) })] })] })] }), _jsx("div", { className: "md:hidden", children: _jsx(BottomNav, {}) })] }));
};
export default NotFound;
