import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router";
import { Circle, Bookmark, Trash2 } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { formatDistanceToNow } from "date-fns";
import { getBuildingImageUrl } from "@/utils/image";
import { getBuildingUrl } from "@/utils/url";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger, } from "@/components/ui/tooltip";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger, } from "@/components/ui/alert-dialog";
export function RecommendationCard({ recommendation, interaction, onDismiss, onRate, onWatchlist }) {
    const { building, recommender } = recommendation;
    const year_completed = building.year_completed;
    const imageUrl = getBuildingImageUrl(building.main_image_url);
    return (_jsxs("div", { className: "bg-surface-card border border-border-default rounded-sm overflow-hidden flex flex-col h-full shadow-none animate-in fade-in zoom-in-95 duration-300", children: [_jsx("div", { className: "relative aspect-[4/3] group cursor-pointer overflow-hidden", children: _jsx(Link, { to: getBuildingUrl(building.id, building.slug, building.short_id), children: imageUrl ? (_jsx("img", { src: imageUrl, alt: building.name, className: "w-full h-full object-cover transition-transform duration-500 group-hover:scale-110" })) : (_jsx("div", { className: "w-full h-full bg-surface-muted flex items-center justify-center text-text-secondary p-4 text-center", children: building.name })) }) }), _jsxs("div", { className: "p-3 flex flex-col flex-1 gap-2", children: [_jsxs("div", { children: [_jsx(Link, { to: getBuildingUrl(building.id, building.slug, building.short_id), className: "hover:underline", children: _jsx("h3", { className: "font-semibold leading-tight line-clamp-1", title: building.name, children: building.name }) }), _jsxs("p", { className: "text-xs text-text-secondary mt-0.5", children: [year_completed ?? "—", " \u2022 ", formatDistanceToNow(new Date(recommendation.created_at)), " ago"] })] }), _jsxs("div", { className: "flex items-center gap-3 bg-surface-muted/30 p-2 rounded-sm my-1", children: [_jsxs(Avatar, { className: "h-8 w-8", children: [_jsx(AvatarImage, { src: recommender.avatar_url || undefined }), _jsx(AvatarFallback, { className: "text-xs", children: recommender.username?.charAt(0) })] }), _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-xs text-text-secondary leading-none", children: "From" }), _jsx("span", { className: "font-semibold text-sm leading-tight", children: recommender.username })] })] }), _jsx("div", { className: "mt-auto grid grid-cols-3 gap-2", children: _jsxs(TooltipProvider, { children: [_jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx(Button, { variant: interaction.rating ? "secondary" : "ghost", size: interaction.rating ? "default" : "icon", className: cn("h-8 w-full rounded-sm transition-colors", interaction.rating
                                                    ? "bg-brand-secondary text-text-primary border border-border-default"
                                                    : "hover:bg-brand-primary hover:text-brand-primary-foreground"), onClick: () => onRate(building), children: interaction.rating ? (_jsxs("span", { className: "flex items-center gap-1 font-bold", children: [_jsx(Circle, { className: "h-3 w-3 fill-brand-primary text-brand-primary" }), " ", interaction.rating] })) : (_jsx(Circle, { className: "h-4 w-4" })) }) }), _jsx(TooltipContent, { children: _jsx("p", { children: interaction.rating ? "Edit Review" : "Rate" }) })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx(Button, { variant: interaction.status === "pending" ? "default" : "secondary", size: "icon", className: cn("h-8 w-full rounded-sm transition-colors", interaction.status === "pending"
                                                    ? "bg-brand-primary text-brand-primary-foreground hover:bg-brand-primary-hover"
                                                    : "hover:bg-brand-primary hover:text-brand-primary-foreground"), onClick: () => onWatchlist(building), children: _jsx(Bookmark, { className: cn("h-4 w-4", interaction.status === "pending" && "fill-brand-primary-foreground") }) }) }), _jsx(TooltipContent, { children: _jsx("p", { children: "Add to Bucket List" }) })] }), _jsxs(AlertDialog, { children: [_jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx(AlertDialogTrigger, { asChild: true, children: _jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-full rounded-md hover:bg-feedback-destructive/20 hover:text-feedback-destructive transition-colors", children: _jsx(Trash2, { className: "h-4 w-4" }) }) }) }), _jsx(TooltipContent, { children: _jsx("p", { children: "Delete" }) })] }), _jsxs(AlertDialogContent, { children: [_jsxs(AlertDialogHeader, { children: [_jsx(AlertDialogTitle, { children: "Delete Recommendation" }), _jsxs(AlertDialogDescription, { children: ["Are you sure you want to delete this recommendation from ", recommender.username, "? This action cannot be undone."] })] }), _jsxs(AlertDialogFooter, { children: [_jsx(AlertDialogCancel, { children: "Cancel" }), _jsx(AlertDialogAction, { onClick: () => onDismiss(recommendation.id), className: "bg-feedback-destructive text-feedback-destructive-foreground hover:bg-feedback-destructive/90", children: "Delete" })] })] })] })] }) })] })] }));
}
