import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { cn } from "@/lib/utils";
import { Eye, Star, MapPin } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { getBuildingImageUrl } from "@/utils/image";
export function LeaderboardCard({ building, rank, type }) {
    const navigate = useNavigate();
    const imageUrl = getBuildingImageUrl(building.main_image_url) || "/placeholder.svg";
    return (_jsxs("div", { className: "group flex items-center gap-4 p-4 border-b border-border-default hover:bg-brand-secondary transition-colors cursor-pointer", onClick: () => navigate(`/building/${building.id}`), children: [_jsxs("div", { className: cn("flex items-center justify-center w-8 h-8 rounded-full font-bold text-sm shrink-0", rank <= 3 ? "bg-brand-primary text-brand-primary-foreground" : "bg-surface-muted text-text-secondary"), children: ["#", rank] }), _jsx("div", { className: "h-12 w-12 rounded-md overflow-hidden shrink-0 border border-border-default/50", children: _jsx("img", { src: imageUrl, alt: building.name, className: "h-full w-full object-cover" }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h4", { className: "font-medium truncate group-hover:text-brand-primary transition-colors", children: building.name }), _jsxs("div", { className: "flex items-center text-xs text-text-secondary gap-1", children: [_jsx(MapPin, { className: "h-3 w-3" }), _jsxs("span", { className: "truncate", children: [building.city || "Unknown City", building.country ? `, ${building.country}` : ""] })] })] }), _jsx("div", { className: "text-right shrink-0", children: type === "visited" ? (_jsxs("div", { className: "flex flex-col items-end", children: [_jsxs("div", { className: "flex items-center gap-1 font-semibold", children: [_jsx(Eye, { className: "h-3.5 w-3.5 text-text-secondary" }), _jsx("span", { children: building.visit_count || 0 })] }), _jsx("span", { className: "text-[10px] text-text-secondary", children: "visits" })] })) : (_jsxs("div", { className: "flex flex-col items-end", children: [_jsxs("div", { className: "flex items-center gap-1 font-semibold text-feedback-warning", children: [_jsx(Star, { className: "h-3.5 w-3.5 fill-current" }), _jsx("span", { children: building.avg_rating || 0 })] }), _jsxs("span", { className: "text-[10px] text-text-secondary", children: ["(", building.rating_count, " votes)"] })] })) })] }));
}
