import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useLeaderboard } from "../hooks/useLeaderboard";
import { LeaderboardCard } from "./LeaderboardCard";
import { Trophy, TrendingUp, Loader2 } from "lucide-react";
export function LeaderboardDialog({ open, onOpenChange }) {
    const { leaderboard, isLoading } = useLeaderboard();
    return (_jsx(Dialog, { open: open, onOpenChange: onOpenChange, children: _jsxs(DialogContent, { className: "sm:max-w-md max-h-[85vh] flex flex-col", children: [_jsxs(DialogHeader, { children: [_jsxs(DialogTitle, { className: "flex items-center gap-2", children: [_jsx(Trophy, { className: "h-5 w-5 text-amber-500" }), "Building Leaderboards"] }), _jsx(DialogDescription, { children: "Discover the most popular and highly rated buildings in our community." })] }), isLoading ? (_jsx("div", { className: "flex items-center justify-center py-12", children: _jsx(Loader2, { className: "h-8 w-8 animate-spin text-text-secondary" }) })) : (_jsxs(Tabs, { defaultValue: "most_visited", className: "flex-1 flex flex-col min-h-0", children: [_jsxs(TabsList, { className: "grid w-full grid-cols-2 mb-2", children: [_jsxs(TabsTrigger, { value: "most_visited", className: "gap-2", children: [_jsx(TrendingUp, { className: "h-4 w-4" }), "Most Visited"] }), _jsxs(TabsTrigger, { value: "top_rated", className: "gap-2", children: [_jsx(Trophy, { className: "h-4 w-4" }), "Top Rated"] })] }), _jsxs(ScrollArea, { className: "flex-1 -mx-2 px-2", children: [_jsx(TabsContent, { value: "most_visited", className: "mt-0 space-y-1 pb-4", children: leaderboard?.most_visited?.length === 0 ? (_jsx("div", { className: "text-center py-8 text-text-secondary", children: "No stats available yet." })) : (leaderboard?.most_visited?.map((building, index) => (_jsx(LeaderboardCard, { building: building, rank: index + 1, type: "visited" }, building.id)))) }), _jsx(TabsContent, { value: "top_rated", className: "mt-0 space-y-1 pb-4", children: leaderboard?.top_rated?.length === 0 ? (_jsx("div", { className: "text-center py-8 text-text-secondary", children: "No rated buildings yet (min. 3 votes required)." })) : (leaderboard?.top_rated?.map((building, index) => (_jsx(LeaderboardCard, { building: building, rank: index + 1, type: "rated" }, building.id)))) })] })] }))] }) }));
}
