-- A building is findable by the people who made it.
--
-- `buildings.search_vector` is maintained by `update_building_search_vector()`
-- from six own columns (name, alt_name, aliases, address, city, country). It has
-- never carried credited architects or firms, so `search_buildings_v2` — the
-- authoritative ranked text search behind /search Find mode and the collection
-- "not in this collection" suggestions — could not find a building by its
-- architect. Searching "zaha" returned *Hanaha* and *Zazzle*: pure trigram
-- neighbours of the letters, with none of Zaha Hadid's five buildings.
--
-- The same query already matched credits in two other places, so the product
-- contradicted itself: `get_buildings_list` (Browse SERP) ILIKEs credit names,
-- and the client-side in-collection filter (`filterCollectionItems.ts`) folds
-- credit names into its haystack. An item you could find *inside* a collection
-- by its architect was unfindable in the database.
--
-- WHY A QUERY-TIME BRANCH AND NOT A WIDER search_vector
-- -----------------------------------------------------
-- Folding credit names into `buildings.search_vector` was the other candidate.
-- It would give token-AND across building *and* credit fields in one tsquery
-- ("zaha london"), which this branch cannot. It was rejected on write cost and
-- on the invariant it would create:
--
--   * Every write to `building_credits` (31,563 rows today) would have to
--     UPDATE the parent building — a heap rewrite plus a GIN index update per
--     credit touched. A bulk credit import would double-write `buildings`.
--   * Renaming a company or person (16,447 companies) would have to fan out to
--     every building it is credited on — one firm can hold hundreds.
--   * It adds a third table whose writes must remember to refresh a column on a
--     different table, enforced only by a trigger nobody sees. This repo has
--     already been bitten twice by exactly that shape of hidden invariant
--     (ADR 0022's merge cycle; the `collections` editor RLS policy).
--
-- The branch below costs nothing at write time and, measured on production,
-- ~10ms at query time — because it goes through indexes that already exist
-- (`people_name_trgm_idx`, `companies_name_trgm_idx`, and the
-- `building_credits` FK indexes). No new index, no backfill, no re-index.
--
-- WHY strict_word_similarity AND NOT similarity/ILIKE
-- ---------------------------------------------------
-- Measured against production's 16,447 company names:
--
--   query            target                        similarity  word_sim  strict
--   "zaha"           Zaha Hadid Architects              0.227     1.000    1.000
--   "oma"            Office for Metropolitan …(OMA)     0.100     1.000    1.000
--   "foster partners" Foster + Partners                 1.000     1.000    1.000
--   "zha hadid"      Zaha Hadid Architects  (typo)      0.333     0.700    0.615
--   "zaha"           Hanaha                 (noise)     0.200     0.400    0.200
--   "ar"             Zaha Hadid Architects  (noise)         —     1.000    0.167
--
-- `similarity` is whole-string, so it scores a real firm name below the noise
-- floor as soon as the firm has a suffix ("… Architects"). Plain
-- `word_similarity` fixes that but matches any *prefix* of any word, so "ar"
-- matched 4,938 of 16,447 companies. `strict_word_similarity` requires the
-- matched extent to be whole words: every real query above lands on 1.000,
-- three-letter firm names (OMA, BIG, SOM, MVRDV) included, typos stay at ~0.6,
-- and the noise collapses. One threshold, 0.6, separates them cleanly.
--
-- The 0.6 threshold is written as an explicit `strict_word_similarity(…) >= 0.6`
-- predicate, and candidates are generated by two index-driven predicates OR'd
-- ahead of it. That split is deliberate:
--
--   * The explicit predicate is what decides the match, but it is NOT indexable
--     — on its own it seq-scans all 16,447 companies (measured: 380ms vs 10ms).
--   * `name ILIKE '%query%'` and `query <<% name` are both served by
--     `companies_name_trgm_idx` / `people_name_trgm_idx`, and the planner
--     BitmapOrs the two scans over the one index (verified with EXPLAIN).
--   * `<<%` reads `pg_trgm.strict_word_similarity_threshold` (default 0.6),
--     which is what buys typo tolerance ("zha hadid" → Zaha Hadid Architects).
--     Nothing in this codebase sets that GUC. If a session ever raised it, the
--     ILIKE path still finds every exact substring, so the branch degrades to
--     "no typo tolerance" rather than to "no architect search".
--
-- A function-level `SET pg_trgm.strict_word_similarity_threshold` would have
-- pinned the GUC, but it cannot be used here: on Supabase the `postgres` role
-- may only put an extension GUC in a function's SET clause while that
-- extension's library happens to be loaded in the backend, so `CREATE FUNCTION`
-- fails with "permission denied to set parameter" depending on which pooled
-- backend runs the migration. Correctness must not hinge on that, hence the
-- explicit predicate above.
--
-- Queries under three characters skip the credit branch. `strict_word_similarity`
-- treats a short query as a whole word, so "de" legitimately matches 208 firms
-- and would bury a two-letter name search under other people's buildings. Three
-- characters is where firm acronyms start and where the trigram index becomes
-- usable anyway.
--
-- RANKING: a credit match adds `0.35 × strict_word_similarity` to rank_score.
-- Calibrated against production scores: an exact name hit is 0.87–1.08, a good
-- name hit 0.27, and trigram noise tops out at 0.19–0.21. A perfect credit
-- match therefore lands at ~0.41–0.45 — comfortably clear of the 0.2 floor the
-- collection suggestions apply, and still below a building the user named
-- outright. A typo'd credit match (~0.615) lands at ~0.29, still above the
-- floor. Buildings that match by name score exactly what they scored before:
-- the new term is 0 for them.
--
-- types-neutral: body-only CREATE OR REPLACE. The signature and RETURNS TABLE
-- are unchanged, so gen-types is a no-op.
--
-- Body copied verbatim from 20271175000000 (the current production definition)
-- with only the changes described above.

CREATE OR REPLACE FUNCTION public.search_buildings_v2(p_query text, p_limit integer DEFAULT 20, p_offset integer DEFAULT 0, p_filters jsonb DEFAULT '{}'::jsonb)
 RETURNS TABLE(id uuid, name text, slug text, alt_name text, hero_image_url text, lat double precision, lng double precision, city text, country text, year_completed integer, popularity_score integer, tier_rank text, construction_status text, credit_names text[], rank_score double precision, short_id integer, locality_country_code text, locality_city_slug text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_query               text;
  v_tsquery             tsquery;
  v_category_id         uuid;
  v_typology_ids        uuid[];
  v_attribute_ids       uuid[];
  v_credit_company_id   uuid;
  v_credit_roles        text[];
  v_construction_statuses text[];
  v_exclude_construction_statuses text[];
  v_size_categories     text[];
  v_min_size_sqm        numeric;
  v_max_size_sqm        numeric;
  v_min_storeys         int;
  v_max_storeys         int;
  v_award_id            uuid;
  v_award_outcome       text;
  v_award_year_from     int;
  v_award_year_to       int;
  v_cities_filter       text[];
  v_country_filter      text;
  v_year                int;
  v_centuries           int[];
  v_access_levels       text[];
  v_access_logistics    text[];
  v_access_costs        text[];
  v_collections         uuid[];
  v_folders             uuid[];
  v_rated_by            text[];
  v_filter_contacts     boolean := false;
  v_contact_min_rating  int := 0;
BEGIN
  v_query := NULLIF(trim(p_query), '');
  IF v_query IS NULL THEN
    RETURN;
  END IF;

  BEGIN
    v_tsquery := websearch_to_tsquery('simple', v_query);
  EXCEPTION WHEN OTHERS THEN
    v_tsquery := NULL;
  END;

  IF p_filters IS NOT NULL THEN
    IF p_filters ? 'category_id' AND p_filters->>'category_id' IS NOT NULL THEN
      BEGIN v_category_id := (p_filters->>'category_id')::uuid; EXCEPTION WHEN OTHERS THEN v_category_id := NULL; END;
    END IF;
    IF p_filters ? 'typology_ids' AND jsonb_typeof(p_filters->'typology_ids') = 'array' THEN
      BEGIN SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'typology_ids')::uuid) INTO v_typology_ids; EXCEPTION WHEN OTHERS THEN v_typology_ids := NULL; END;
    END IF;
    IF p_filters ? 'attribute_ids' AND jsonb_typeof(p_filters->'attribute_ids') = 'array' THEN
      BEGIN SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'attribute_ids')::uuid) INTO v_attribute_ids; EXCEPTION WHEN OTHERS THEN v_attribute_ids := NULL; END;
    END IF;
    IF p_filters ? 'credit_company_id' AND p_filters->>'credit_company_id' IS NOT NULL THEN
      BEGIN v_credit_company_id := (p_filters->>'credit_company_id')::uuid; EXCEPTION WHEN OTHERS THEN v_credit_company_id := NULL; END;
    END IF;
    IF p_filters ? 'credit_roles' AND jsonb_typeof(p_filters->'credit_roles') = 'array' THEN
      SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'credit_roles')) INTO v_credit_roles;
    END IF;
    IF p_filters ? 'construction_statuses' AND jsonb_typeof(p_filters->'construction_statuses') = 'array' THEN
      SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'construction_statuses')) INTO v_construction_statuses;
    END IF;
    IF p_filters ? 'exclude_construction_statuses' AND jsonb_typeof(p_filters->'exclude_construction_statuses') = 'array' THEN
      SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'exclude_construction_statuses')) INTO v_exclude_construction_statuses;
    END IF;
    IF p_filters ? 'size_categories' AND jsonb_typeof(p_filters->'size_categories') = 'array' THEN
      SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'size_categories')) INTO v_size_categories;
    END IF;
    IF p_filters ? 'min_size_sqm' AND p_filters->>'min_size_sqm' IS NOT NULL THEN
      BEGIN v_min_size_sqm := (p_filters->>'min_size_sqm')::numeric; EXCEPTION WHEN OTHERS THEN v_min_size_sqm := NULL; END;
    END IF;
    IF p_filters ? 'max_size_sqm' AND p_filters->>'max_size_sqm' IS NOT NULL THEN
      BEGIN v_max_size_sqm := (p_filters->>'max_size_sqm')::numeric; EXCEPTION WHEN OTHERS THEN v_max_size_sqm := NULL; END;
    END IF;
    IF p_filters ? 'min_storeys' AND p_filters->>'min_storeys' IS NOT NULL THEN
      BEGIN v_min_storeys := (p_filters->>'min_storeys')::int; EXCEPTION WHEN OTHERS THEN v_min_storeys := NULL; END;
    END IF;
    IF p_filters ? 'max_storeys' AND p_filters->>'max_storeys' IS NOT NULL THEN
      BEGIN v_max_storeys := (p_filters->>'max_storeys')::int; EXCEPTION WHEN OTHERS THEN v_max_storeys := NULL; END;
    END IF;
    IF p_filters ? 'award_id' AND p_filters->>'award_id' IS NOT NULL THEN
      BEGIN v_award_id := (p_filters->>'award_id')::uuid; EXCEPTION WHEN OTHERS THEN v_award_id := NULL; END;
    END IF;
    IF p_filters ? 'award_outcome' AND p_filters->>'award_outcome' IS NOT NULL THEN
      v_award_outcome := p_filters->>'award_outcome';
    END IF;
    IF p_filters ? 'award_year_from' AND p_filters->>'award_year_from' IS NOT NULL THEN
      BEGIN v_award_year_from := (p_filters->>'award_year_from')::int; EXCEPTION WHEN OTHERS THEN v_award_year_from := NULL; END;
    END IF;
    IF p_filters ? 'award_year_to' AND p_filters->>'award_year_to' IS NOT NULL THEN
      BEGIN v_award_year_to := (p_filters->>'award_year_to')::int; EXCEPTION WHEN OTHERS THEN v_award_year_to := NULL; END;
    END IF;
    IF p_filters ? 'cities' AND jsonb_typeof(p_filters->'cities') = 'array' THEN
      SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'cities')) INTO v_cities_filter;
    END IF;
    IF p_filters ? 'country' AND p_filters->>'country' IS NOT NULL THEN
      v_country_filter := p_filters->>'country';
    END IF;
    IF p_filters ? 'year' AND p_filters->>'year' IS NOT NULL THEN
      BEGIN v_year := (p_filters->>'year')::int; EXCEPTION WHEN OTHERS THEN v_year := NULL; END;
    END IF;
    IF p_filters ? 'centuries' AND jsonb_typeof(p_filters->'centuries') = 'array' THEN
      BEGIN
        SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'centuries')::int) INTO v_centuries;
      EXCEPTION WHEN OTHERS THEN v_centuries := NULL;
      END;
    END IF;
    IF p_filters ? 'access_levels' AND jsonb_typeof(p_filters->'access_levels') = 'array' THEN
      SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'access_levels')) INTO v_access_levels;
    END IF;
    IF p_filters ? 'access_logistics' AND jsonb_typeof(p_filters->'access_logistics') = 'array' THEN
      SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'access_logistics')) INTO v_access_logistics;
    END IF;
    IF p_filters ? 'access_costs' AND jsonb_typeof(p_filters->'access_costs') = 'array' THEN
      SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'access_costs')) INTO v_access_costs;
    END IF;
    IF p_filters ? 'collections' AND jsonb_typeof(p_filters->'collections') = 'array' THEN
      BEGIN SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'collections')::uuid) INTO v_collections; EXCEPTION WHEN OTHERS THEN v_collections := NULL; END;
    END IF;
    IF p_filters ? 'folders' AND jsonb_typeof(p_filters->'folders') = 'array' THEN
      BEGIN SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'folders')::uuid) INTO v_folders; EXCEPTION WHEN OTHERS THEN v_folders := NULL; END;
    END IF;
    IF p_filters ? 'rated_by' AND jsonb_typeof(p_filters->'rated_by') = 'array' THEN
      SELECT ARRAY(SELECT jsonb_array_elements_text(p_filters->'rated_by')) INTO v_rated_by;
    END IF;
    v_filter_contacts := COALESCE((p_filters->>'filter_contacts')::boolean, false);
    v_contact_min_rating := COALESCE((p_filters->>'contact_min_rating')::int, 0);
  END IF;

  RETURN QUERY
  -- Credited people and firms whose name contains the query as whole words,
  -- resolved once per query and then mapped to buildings. Kept out of the main
  -- WHERE as a pre-computed set on purpose: as an inline `OR EXISTS (…)` the
  -- planner cannot reach `people_name_trgm_idx` / `companies_name_trgm_idx` and
  -- re-evaluates the join for all 18k buildings.
  --
  -- `IS DISTINCT FROM 'hidden'` rather than the `NOT IN ('hidden')` the
  -- credit_names lateral below uses: NOT IN silently drops a NULL status. There
  -- are no NULL statuses in production, so the two agree today — the null-safe
  -- form is simply the one a new branch should be written in.
  WITH credit_hits AS MATERIALIZED (
    SELECT h.building_id, MAX(h.sim) AS credit_sim
    FROM (
      SELECT bc.building_id, strict_word_similarity(v_query, p.name) AS sim
      FROM public.people p
      JOIN public.building_credits bc ON bc.person_id = p.id
      WHERE length(v_query) >= 3
        AND (p.name ILIKE '%' || v_query || '%' OR v_query <<% p.name)
        AND strict_word_similarity(v_query, p.name) >= 0.6
        AND bc.status IS DISTINCT FROM 'hidden'::public.credit_status_enum
      UNION ALL
      SELECT bc.building_id, strict_word_similarity(v_query, c.name) AS sim
      FROM public.companies c
      JOIN public.building_credits bc ON bc.company_id = c.id
      WHERE length(v_query) >= 3
        AND (c.name ILIKE '%' || v_query || '%' OR v_query <<% c.name)
        AND strict_word_similarity(v_query, c.name) >= 0.6
        AND bc.status IS DISTINCT FROM 'hidden'::public.credit_status_enum
    ) h
    GROUP BY h.building_id
  )
  SELECT
    b.id,
    b.name,
    b.slug,
    b.alt_name,
    main_image_url(b)                   AS hero_image_url,
    ST_Y(b.location::geometry)          AS lat,
    ST_X(b.location::geometry)          AS lng,
    b.city,
    b.country,
    b.year_completed,
    b.popularity_score,
    b.tier_rank::text                   AS tier_rank,
    b.status::text                      AS construction_status,
    COALESCE(credits_lateral.names, '{}'::text[]) AS credit_names,
    (
      0.6 * COALESCE(ts_rank_cd(b.search_vector, v_tsquery), 0.0)
      + 0.3 * GREATEST(
          similarity(b.name, v_query),
          COALESCE(similarity(b.alt_name, v_query), 0.0)
        )
      + 0.1 * (
          log(GREATEST(1.0, COALESCE(b.popularity_score, 0)::float + 100.0))
          / log(1100.0)
        )
      -- 0 for every building that did not match by credit, so a name hit keeps
      -- exactly the score it had before this migration.
      + 0.35 * COALESCE(ch.credit_sim, 0.0)
    )                                   AS rank_score,
    b.short_id,
    loc.country_code                    AS locality_country_code,
    loc.city_slug                       AS locality_city_slug
  FROM public.buildings b
  LEFT JOIN public.localities loc ON b.locality_id = loc.id
  LEFT JOIN credit_hits ch ON ch.building_id = b.id
  LEFT JOIN LATERAL (
    SELECT array_agg(DISTINCT COALESCE(p.name, c.name))
           FILTER (WHERE COALESCE(p.name, c.name) IS NOT NULL) AS names
    FROM public.building_credits bc
    LEFT JOIN public.people    p ON p.id = bc.person_id
    LEFT JOIN public.companies c ON c.id = bc.company_id
    WHERE bc.building_id = b.id
      AND bc.status NOT IN ('hidden')
  ) credits_lateral ON true
  WHERE
    (b.is_deleted IS FALSE OR b.is_deleted IS NULL)
    -- NOTE: no `b.location IS NOT NULL` gate — a name/text search is
    -- authoritative and must surface a building even without coordinates.
    -- lat/lng come back NULL for those rows; the client tolerates it.
    AND (
      (v_tsquery IS NOT NULL AND b.search_vector @@ v_tsquery)
      OR similarity(b.name, v_query) >= 0.2
      OR COALESCE(similarity(b.alt_name, v_query), 0.0) >= 0.2
      -- The credited architect or firm is a name the building answers to.
      OR ch.credit_sim IS NOT NULL
    )
    AND (v_category_id IS NULL OR b.functional_category_id = v_category_id)
    AND (v_typology_ids IS NULL OR cardinality(v_typology_ids) = 0 OR EXISTS (
      SELECT 1 FROM public.building_functional_typologies bft
      WHERE bft.building_id = b.id AND bft.typology_id = ANY(v_typology_ids)
    ))
    AND (v_attribute_ids IS NULL OR cardinality(v_attribute_ids) = 0 OR EXISTS (
      SELECT 1 FROM public.building_attributes batt
      WHERE batt.building_id = b.id AND batt.attribute_id = ANY(v_attribute_ids)
    ))
    AND public.building_matches_credit_filters(b.id, v_credit_company_id, v_credit_roles)
    AND (v_construction_statuses IS NULL OR cardinality(v_construction_statuses) = 0
         OR b.status::text = ANY(v_construction_statuses))
    AND (v_exclude_construction_statuses IS NULL OR cardinality(v_exclude_construction_statuses) = 0
         OR b.status IS NULL OR NOT (b.status::text = ANY(v_exclude_construction_statuses)))
    AND (v_size_categories IS NULL OR cardinality(v_size_categories) = 0
         OR b.size_category = ANY(v_size_categories))
    AND (v_min_size_sqm IS NULL OR v_min_size_sqm = 0 OR b.size_sqm >= v_min_size_sqm)
    AND (v_max_size_sqm IS NULL OR b.size_sqm <= v_max_size_sqm)
    AND (v_min_storeys IS NULL OR v_min_storeys <= 1 OR b.storeys >= v_min_storeys)
    AND (v_max_storeys IS NULL OR b.storeys <= v_max_storeys)
    AND (v_award_id IS NULL OR b.id IN (
      SELECT building_id
      FROM public.get_buildings_with_awards(v_award_id, v_award_outcome, v_award_year_from, v_award_year_to)
    ))
    AND (v_cities_filter IS NULL OR cardinality(v_cities_filter) = 0
         OR b.city = ANY(v_cities_filter))
    AND (v_country_filter IS NULL OR b.country = v_country_filter)
    AND (v_year IS NULL OR b.year_completed = v_year)
    AND (v_centuries IS NULL OR cardinality(v_centuries) = 0
         OR ((0 = ANY(v_centuries) AND b.century IS NOT NULL AND b.century < 1)
             OR (b.century IS NOT NULL AND b.century > 0 AND b.century = ANY(v_centuries))))
    AND (v_access_levels IS NULL OR cardinality(v_access_levels) = 0
         OR b.access_level::text = ANY(v_access_levels))
    AND (v_access_logistics IS NULL OR cardinality(v_access_logistics) = 0
         OR b.access_logistics::text = ANY(v_access_logistics))
    AND (v_access_costs IS NULL OR cardinality(v_access_costs) = 0
         OR b.access_cost::text = ANY(v_access_costs))
    AND (
      ((v_collections IS NULL OR cardinality(v_collections) = 0) AND (v_folders IS NULL OR cardinality(v_folders) = 0))
      OR b.id IN (SELECT building_id FROM public.get_buildings_in_collections(v_collections, v_folders))
    )
    AND (
      ((v_rated_by IS NULL OR cardinality(v_rated_by) = 0) AND COALESCE(v_filter_contacts, false) = false)
      OR public.building_matches_contact_filters(b.id, v_rated_by, v_filter_contacts, v_contact_min_rating)
    )
  ORDER BY rank_score DESC
  LIMIT p_limit OFFSET p_offset;
END;
$function$;

-- Per `_TEMPLATE_rpc.sql.txt`: a CREATE OR REPLACE resets nothing, but PUBLIC
-- holds EXECUTE on a new function by default and the earlier migrations in this
-- chain never took it back. Named roles only, so the grant above is the whole
-- story.
REVOKE EXECUTE ON FUNCTION public.search_buildings_v2(text, integer, integer, jsonb) FROM public;
GRANT EXECUTE ON FUNCTION public.search_buildings_v2(text, integer, integer, jsonb) TO anon, authenticated, service_role;
