-- Rename credit_role_enum values from person-based (e.g. 'design_architect') 
-- to discipline-based (e.g. 'design_architecture') to better represent 
-- company-linked credits.

ALTER TYPE public.credit_role_enum RENAME VALUE 'design_architect' TO 'design_architecture';
ALTER TYPE public.credit_role_enum RENAME VALUE 'architect_of_record' TO 'architecture_of_record';
ALTER TYPE public.credit_role_enum RENAME VALUE 'executive_architect' TO 'executive_architecture';
ALTER TYPE public.credit_role_enum RENAME VALUE 'interior_architect' TO 'interior_architecture';
ALTER TYPE public.credit_role_enum RENAME VALUE 'landscape_architect' TO 'landscape_architecture';
ALTER TYPE public.credit_role_enum RENAME VALUE 'urban_designer' TO 'urban_design';
ALTER TYPE public.credit_role_enum RENAME VALUE 'conservation_architect' TO 'conservation_architecture';
ALTER TYPE public.credit_role_enum RENAME VALUE 'structural_engineer' TO 'structural_engineering';
ALTER TYPE public.credit_role_enum RENAME VALUE 'mep_engineer' TO 'mep_engineering';
ALTER TYPE public.credit_role_enum RENAME VALUE 'civil_engineer' TO 'civil_engineering';
ALTER TYPE public.credit_role_enum RENAME VALUE 'geotechnical_engineer' TO 'geotechnical_engineering';
ALTER TYPE public.credit_role_enum RENAME VALUE 'facade_engineer' TO 'facade_engineering';
ALTER TYPE public.credit_role_enum RENAME VALUE 'wind_consultant' TO 'wind_consultancy';
ALTER TYPE public.credit_role_enum RENAME VALUE 'acoustic_consultant' TO 'acoustic_consultancy';
ALTER TYPE public.credit_role_enum RENAME VALUE 'fire_engineer' TO 'fire_engineering';
ALTER TYPE public.credit_role_enum RENAME VALUE 'lighting_designer' TO 'lighting_design';
ALTER TYPE public.credit_role_enum RENAME VALUE 'developer' TO 'development';
ALTER TYPE public.credit_role_enum RENAME VALUE 'main_contractor' TO 'main_contracting';
ALTER TYPE public.credit_role_enum RENAME VALUE 'project_manager' TO 'project_management';
ALTER TYPE public.credit_role_enum RENAME VALUE 'cost_consultant' TO 'cost_consultancy';
ALTER TYPE public.credit_role_enum RENAME VALUE 'planning_consultant' TO 'planning_consultancy';
ALTER TYPE public.credit_role_enum RENAME VALUE 'graphic_wayfinding_designer' TO 'graphic_wayfinding_design';
ALTER TYPE public.credit_role_enum RENAME VALUE 'art_consultant' TO 'art_consultancy';
ALTER TYPE public.credit_role_enum RENAME VALUE 'sustainability_consultant' TO 'sustainability_consultancy';
ALTER TYPE public.credit_role_enum RENAME VALUE 'heritage_consultant' TO 'heritage_consultancy';
